apiVersion: v1
kind: ImageStream
metadata:
  name: tomcat
spec:
  tags:
  - annotations:
      supports: tomcat:6.0.48,jre7,java
      tags: tomcat,java
      version: "6.0.48"
    from:
      kind: DockerImage
      name: docker.io/tomcat:6.0.48-jre7
    name: "6.0.48"
  - annotations:
      supports: web,java
      tags: tomcat,java
    from:
      kind: ImageStreamTag
      name: "6.0.48"
    name: "6.0.48-jre7"
